### ISSUE TITLE
Process Death discussion 

### ISSUE THREAD

**Issue by pablichjenkov** [sellmair/evas#11]
Does the library support Process Death 💀? If the App process gets killed by the system and the App is relaunched, does the state recover automatically to the same value it had before the process was killed?
Or persisting relevant process death recovery data is left to the developer according to the App business logic.

**Comment by sellmair** [comment]
This library has no opinions on how to handle process death: 
My take: Handle it in any way you prefer: Store the relevant data and restore ist at the correct lifecycle methods!

**Comment by pablichjenkov** [comment]
Got it
