### ISSUE TITLE
How to use this library in a simple Kotlin project

### ISSUE THREAD

**Issue by shirishpandharikar** [sellmair/evas#5]
Thanks for the wonderful library. I was trying to use this library in a non-Android project. The project is compiled using Maven. However even after adding the dependency I'm not able to see the required class for import. Is there anything I'm missing?

```xml
<dependency>
    <groupId>io.sellmair</groupId>
    <artifactId>evas</artifactId>
    <version>1.0.0-RC</version>
</dependency>
```

**Comment by sellmair** [comment]
I think for maven consumers it should work, using the `evas-jvm` instead of `evas`. I will check today evening ☺️

**Comment by sellmair** [comment]
I double checked ✅
```xml
        <dependency>
            <groupId>io.sellmair</groupId>
            <artifactId>evas-jvm</artifactId>
            <version>1.0.0-RC</version>
        </dependency>
```

Works. As evas supports many platforms, maven projects require to specify the `-jvm` platform

**Comment by shirishpandharikar** [comment]
Verified with the suggested `evas-jvm` dependency. Thanks. Would be good to add it to the readme for JVM users.

**Comment by shirishpandharikar** [comment]
Verified with the suggested `evas-jvm` dependency. Thanks. Would be good to add it to the readme for JVM users.
